### ISSUE TITLE
Update checkValueTypeCompliance to support upper case boolean values

### ISSUE THREAD

**Issue by vshioshvili** [pepfar-datim/datim-validation#102]
Update the boolean and true only types to accept uppercase values in addition to currently accepted all lower case, sentence case, and 1/0 values. DHIS2 accepts all upper case, and Excel has a tendency to make true and false all upper case in a csv file, causing validation issues, even though they are valid values from DHIS2 perspective.

https://github.com/pepfar-datim/datim-validation/blob/master/R/checkValueTypeCompliance.R#L37
https://github.com/pepfar-datim/datim-validation/blob/master/R/checkValueTypeCompliance.R#L38

**Comment by jason-p-pickering** [comment]
Should be addressed in v1.2.0.
