### ISSUE TITLE
checkValueTypeCompliance not validating DATETIME data type correctly

### ISSUE THREAD

**Issue by Hiwot-Chichaybelu** [pepfar-datim/datim-validation#120]
https://github.com/pepfar-datim/datim-validation/blob/d1e0a1e002d681ab0896758f5cfb2edbce612a88/R/checkValueTypeCompliance.R#L49 
According to the regex in the above line DATETIME is expected to have yyyy-mm-dd hh:mm:ss format. However, the acceptable format in DATIM is yyyy-mm-ddThh:mm:ss.

**Comment by jason-p-pickering** [comment]
Should be fixed in 8df92deff7c34ac48dd4abcdba68bfa24c7795fa
