### ISSUE TITLE
Bug when using a  semicolon delimited csv

### ISSUE THREAD

**Issue by crysiscore** [pepfar-datim/datim-validation#134]
Running
d <- d2Parser(filename = datafile, type = "csv", datastream = "RESULTS") 

using a semicolon delimited csv the execution stops and shows  the following error
Error in `[.data.frame`(data, 1:3) : undefined columns selected.

could you please add a function to guess which delimiter the csv is using , and use the sep parameter from the read.csv function?

 if (type == "csv") {
    data <- read.csv(filename, header = hasHeader,  stringsAsFactors = FALSE)  <--- bug here
    data[] <- lapply(data, stringr::str_trim)
    names(data)[seq_len(ncol(data))] <- header[seq_len(ncol(data))]
    missing_required <- !complete.cases(data[, 1:3])
.........

**Comment by vshioshvili** [comment]
@crysiscore please note that datim-validation package is consistent with DHIS2, which expects commas as separator in comma-separated values (CSV) file. This is not a bug. We can put it as a feature request, but I don't think the team will be adding it in the near future.
