### ISSUE TITLE
http request timeout

### ISSUE THREAD

**Issue by vshioshvili** [pepfar-datim/datim-validation#79]
In a number of places the code has timeout hardcoded at 60 seconds. In certain situations that is not enough - e.g. https://github.com/jason-p-pickering/datim-validation/blob/master/R/checkDataElementOrgunitValidity.R#L54 - when running datim-validation against SIMS data, the referenced code tries to load org units for two data sets, one of which is associated with all facilities in the entire org units tree (Global) of DATIM, and it takes longer than 60 seconds, resulting in timeouts.

**Comment by jason-p-pickering** [comment]
This method has been completely reimplemented, and I do not think this timeout will be an issue any longer. However, I have also added the ability alter the timeout (across the entire project) with an environment variable. If this is set (HTTP_TIMEOUT) the timeout can be controlled by the user. The default is 300 seconds but could be altered if required for your specific setup.
