### ISSUE TITLE
Consider expanding getCurrentMERDataSets to include NAT data sets

### ISSUE THREAD

**Issue by vshioshvili** [pepfar-datim/datim-validation#84]
@jason-p-pickering  DATIM user requested assistance with a file that includes NAT level  data (HRH_STAFF_NAT data element to be exact). As getCurrentMERDataSets method does not include data sets other than community, facility, and medical store level, it reports errors, while they are not really errors.

Can we consider expanding it to include other data sets?
https://github.com/jason-p-pickering/datim-validation/blob/f6020cfc6b9bcbf292c91ac7ec74a93f67f5cd39/R/getDataSets.R#L58

**Comment by jason-p-pickering** [comment]
@vshioshvili can you see if this has been fixed in 41eea905adfaf2b5da4cc581f91e8c06d095cfe3? If so, please close this issue.

**Comment by vshioshvili** [comment]
@jason-p-pickering Yes and no

1) not sure if we should include the OU level data set as well, not just facility;
2) but more importantly, for the fix to work, we need to allow default mechanism. d2parser rejects(https://github.com/jason-p-pickering/datim-validation/blob/master/R/d2Parser.R#L51) default mechanism as it is not included in the list of valid mechanisms (https://github.com/jason-p-pickering/datim-validation/blob/master/R/getMechanismsMap.R#L17)

**Comment by jason-p-pickering** [comment]
@vshioshvili  I think this latest [PR](https://github.com/pepfar-datim/datim-validation/pull/109) should address most of this. Support for the NAT level datasets has been added, along with the default mechanism. Note, that by allowing the default mechanism as a possible mechanism, this does mean we will need to check all "usual" MER data to be sure that it is not being submitted against the default mech. The function `checkDataElementMechValidity` will return all invalid data element/attribute option combinations. Stated another way, this should check that NAT data is submitted for the default mech, which normal MER data is submitted against a true mechanism.
