### ISSUE TITLE
evaluateValidation.R - SKIP_IF_ALL_VALUES_MISSING behavior different from DHIS2

### ISSUE THREAD

**Issue by vshioshvili** [pepfar-datim/datim-validation#92]
@jason-p-pickering [this block](https://github.com/jason-p-pickering/datim-validation/blob/f6020cfc6b9bcbf292c91ac7ec74a93f67f5cd39/R/evaluateValidation.R#L85) appears to cause datim-validation to behave differently than DHIS2.

According to the code referenced above, if one of the sides is declared as `NEVER_SKIP`, rule is evaluated, not matter what the other side of the expression is.

In DHIS2, if one side is `SKIP_IF_ALL_VALUES_MISSING` and there are no values reported, validation rule is skipped even if the other side says `NEVER_SKIP`.

I think the block should actually be something like this:

```
  #Keep rules which should  be evaluated
  keep_these_rules <- (
    (
      matches$leftSide.missingValueStrategy == "NEVER_SKIP" |
        (matches$leftSide.missingValueStrategy == "SKIP_IF_ANY_VALUE_MISSING" & matches$leftSide.ops != matches$leftSide.count) |
        (matches$leftSide.missingValueStrategy == "SKIP_IF_ALL_VALUES_MISSING" & matches$leftSide.count != 0)
    )
  &
    (
      matches$rightSide.missingValueStrategy == "NEVER_SKIP" |
        (matches$rightSide.missingValueStrategy == "SKIP_IF_ANY_VALUE_MISSING" & matches$rightSide.ops != matches$rightSide.count) |
        (matches$rightSide.missingValueStrategy == "SKIP_IF_ALL_VALUES_MISSING" & matches$rightSide.count != 0)
    )
  )
```

**Comment by jason-p-pickering** [comment]
@vshioshvili is this still an issue?

**Comment by vshioshvili** [comment]
@jason-p-pickering not an issue - we can close this
